#!/bin/bash

line="$(free -h | grep Mem)"
echo "$line" > ~/.config/xmobar/barScripts/temp/memoryTemp
read title total used a b c d < ~/.config/xmobar/barScripts/temp/memoryTemp

line="$(free | grep Mem)"
echo "$line" > ~/.config/xmobar/barScripts/temp/memoryTemp
read title totalB usedB a b c d <  ~/.config/xmobar/barScripts/temp/memoryTemp

usedB=$((100 * usedB))

percent="$(echo $usedB / $totalB | bc -l | cut -c -4)"

echo -e "$used/$total ($percent%)"
